source 'https://rubygems.org'

gem 'sinatra'
gem 'rack-stream', :path => File.expand_path('../../../', __FILE__)
gem 'faraday'
gem 'thin'
gem 'redis'
gem 'hiredis'
gem 'json'

group :ruby19 do
  gem 'debugger'
end